#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
total = 0
def fib(n1,n2):
	global total
	if n2 % 2 == 0: total += n2;
	if n1 < 4000000 and n2 < 4000000: fib(n2, n1 + n2)
fib(1,2)
print total