# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
# The first ten terms would be:1,3,6,10,15,21,28,36,45,55,...
#     28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?
import math
def divisors(num):
	divs = 2 # 1 and num
	for n in range(2,int(math.ceil(num**0.5))+1):
		if num % n == 0:
			divs += 2
	return divs
largest = 0
answer = 0
steps = 0
tri = 0
def triangle(n):
	global tri,steps
	tri += steps	
while largest < 500:
	steps += 1
	triangle(steps)
	divs = divisors(tri)
	if divs > largest:
		largest = divs
		answer = tri
print largest
print answer
